version: "3.8"

services:
  app:
    container_name: e-sports-server
    build: .
    ports:
      - "7010:7010"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: e-sports-db
    environment:
      POSTGRES_DB: esportsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password@2025
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
