apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-sports-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e-sports-server
    metadata:
      labels:
        app: e-sports-server
    spec:
      containers:
        - name: e-sports-server
          image: your-dockerhub-username/ecommerce-app:latest
          ports:
            - containerPort: 7010
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: e-sports-server
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: e-sports-server
